[project]
name = "project-runway"
version = "0.0.1"
description = "Add your description here"
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE.md" }
requires-python = ">=3.12"
dependencies = []
